import { AlertTriangle } from 'lucide-react';
import { LegalPage, LegalSection } from './LegalPage';

export function DataDisclaimerSection() {
  return (
    <LegalPage title="Data Disclaimer" subtitle="Important information about data sources and accuracy" icon={<AlertTriangle className="w-4 h-4" />}>
      <LegalSection heading="Real vs. Demo Data">
        <p>
          Varanasi is currently demonstrated using the provided dataset. Other city views may contain prototype or
          demo data. Demo data should not be interpreted as actual live electricity-grid conditions.
        </p>
      </LegalSection>
      <LegalSection heading="Data Availability">
        <p>
          Data availability, accuracy, and update frequency may vary depending on the connected data source.
          The platform displays the most recent information available, but does not guarantee real-time accuracy
          for all locations.
        </p>
      </LegalSection>
      <LegalSection heading="Demo Data Limitations">
        <p>
          Cities marked as "Demo / Prototype" use simulated values generated to demonstrate the platform's structure
          and scalability. These values are not derived from actual grid telemetry and should not be used for
          operational decision-making. When real data becomes available for a city, the demo dataset will be
          replaced and clearly labeled.
        </p>
      </LegalSection>
      <LegalSection heading="No External Data Provider Claims">
        <p>
          UrjaGrid does not currently claim affiliation with or data from any specific government department,
          electricity board, or external data provider. Such relationships would be disclosed as they are established.
        </p>
      </LegalSection>
      <LegalSection heading="AI-Generated Insights">
        <p>
          AI Insights are generated by analyzing available grid data. They do not use external prediction models
          and should not be treated as forecasts or guaranteed outcomes. Insights for demo cities are based on
          simulated data and are labeled accordingly.
        </p>
      </LegalSection>
      <LegalSection heading="Use of Information">
        <p>
          Information presented on this platform should be used as a supplementary tool for understanding grid
          conditions. Critical operational decisions should always be verified through appropriate professional
          and operational channels.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
